name: agent-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - run: make placeholders:list
      - run: make placeholders:check
      - run: make lint
      - run: make test
      - run: |
          if [[ "${PROFILE:-demo}" == "production" ]]; then
            make placeholders:check
          fi
