name: agent-refresh

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Derive run metadata
        id: meta
        run: |
          echo "run_date=$(date -u +%Y%m%d)" >> "$GITHUB_OUTPUT"
          echo "run_date_human=$(date -u +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
      - name: Run maintainer agent
        run: python src/agent/main.py --output artifacts/agent/report.json --pr-body artifacts/agent/pr_body.md
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: agent/update-${{ steps.meta.outputs.run_date }}
          title: "chore(agent): refresh models/datasets/placeholders – ${{ steps.meta.outputs.run_date_human }}"
          body-path: artifacts/agent/pr_body.md
          commit-message: "chore(agent): refresh analytics catalog"
          labels: 'agent,needs-review,auto'
